### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by pakanek** [tobbebex/GPipe-Core#25]
I tried to follow [GPipe Hello Triangle](http://tobbebex.blogspot.cz/2015/09/gpu-programming-in-haskell-using-gpipe.html) but I get segfault. I tried `Control.Concurrent.forkOS` to run whole main function in bound thread without success.

Backtrace of GPipe-Test
```
(gdb) run
Starting program: /home/mirpa/code/checkout/GPipe-Test/GPipe-Test/.stack-work/install/x86_64-linux/lts-5.5/7.10.3/bin/Main 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff33ff700 (LWP 4207)]
[New Thread 0x7ffff2bfe700 (LWP 4208)]
[New Thread 0x7ffff23fd700 (LWP 4209)]
[New Thread 0x7ffff1bfc700 (LWP 4210)]
cursorPos x1135.0 y331.0, mouseButton1 MouseButtonState'Released, spaceKey KeyState'Released, shouldClose False

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff1bfc700 (LWP 4210)]
0x00007ffff03ce67e in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
(gdb) bt
#0  0x00007ffff03ce67e in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
#1  0x00007ffff03ced41 in ?? () from /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
#2  0x00007ffff0a16155 in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#3  0x00007ffff0a216aa in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#4  0x00007ffff079ccaf in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#5  0x00007ffff076f03e in ?? () from /usr/lib/x86_64-linux-gnu/dri/nouveau_dri.so
#6  0x00000000008ab3a6 in ?? ()
#7  0x00007ffff34a3010 in ?? ()
#8  0x0000000000000000 in ?? () 
(gdb) continue
Continuing.
[Thread 0x7ffff1bfc700 (LWP 4210) exited]
[Thread 0x7ffff23fd700 (LWP 4209) exited]
[Thread 0x7ffff33ff700 (LWP 4207) exited]
[Thread 0x7ffff7fb7740 (LWP 4203) exited]

Program terminated with signal SIGSEGV, Segmentation fault.
The program no longer exists.
(gdb)
```

```
ldd .stack-work/install/x86_64-linux/lts-5.5/7.10.3/bin/Main
        linux-vdso.so.1 (0x00007ffe737f8000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f799f58e000)
        libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f799f2f4000)
        libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f799efb1000)
        libXi.so.6 => /usr/lib/x86_64-linux-gnu/libXi.so.6 (0x00007f799eda1000)
        libXrandr.so.2 => /usr/lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f799eb97000)
        libXxf86vm.so.1 => /usr/lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f799e991000)
        libXcursor.so.1 => /usr/lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f799e786000)
        libXinerama.so.1 => /usr/lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f799e583000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f799e366000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f799e15e000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f799df5b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f799dd57000)
        libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f799dad4000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f799d7d3000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f799d5bd000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f799d212000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f799cfe9000)
        libglapi.so.0 => /usr/lib/x86_64-linux-gnu/libglapi.so.0 (0x00007f799cdbf000)
        libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007f799cbad000)
        libXdamage.so.1 => /usr/lib/x86_64-linux-gnu/libXdamage.so.1 (0x00007f799c9aa000)
        libXfixes.so.3 => /usr/lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f799c7a4000)
        libX11-xcb.so.1 => /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1 (0x00007f799c5a2000)
        libxcb-glx.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0 (0x00007f799c389000)
        libxcb-dri2.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0 (0x00007f799c184000)
        libxcb-dri3.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0 (0x00007f799bf81000)
        libxcb-present.so.0 => /usr/lib/x86_64-linux-gnu/libxcb-present.so.0 (0x00007f799bd7e000)
        libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f799bb77000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f799b955000)
        libxshmfence.so.1 => /usr/lib/x86_64-linux-gnu/libxshmfence.so.1 (0x00007f799b753000)
        libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f799b546000)
        libXrender.so.1 => /usr/lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f799b33c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f799f7a9000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f799b138000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f799af33000)
```

Excerpt from glxinfo
```
...
OpenGL vendor string: nouveau
OpenGL renderer string: Gallium 0.4 on NVA8
OpenGL core profile version string: 3.3 (Core Profile) Mesa 10.3.2
OpenGL core profile shading language version string: 3.30
...
```

```
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

**Comment by pakanek** [comment]
It must have beet my drivers, proprietary drivers fixed this.

**Comment by plredmond** [comment]
Thanks for reporting the issue though! It's good to have the data point that GPipe doesn't currently work with Nouveau. Good luck with your project!
